
import { Geist, Geist_Mono } from "next/font/google";
import { Archivo } from 'next/font/google';
import "./globals.css";
import { headers } from 'next/headers';
import Sidebar from "./sidebar";
import SidebarRecruiter from './sidebar';
import SidebarJobSeeker from './SidebarJobSeeker';
import Toolbox from "./toolbox";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-archivo',
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  manifest: "/manifest.json",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  

  let role = 'recruiter';

 
  
 
  return (
    <html lang="en" className={archivo.variable}>
      <body className="textfont">
        <div style={{ display: 'flex', height: '100vh' }}>
          {/* Sidebar on the left */}
          
          <div className="h-screen flex items-center ml-5 justify-center">
      {role === 'recruiter' ? (
        <SidebarRecruiter/>
      ) : (
        <SidebarJobSeeker />
       
      )}
    </div>
         
          <main className="flex-1 p-2 h-[100vh]  flex flex-col  ">
            {/* Topbar */}
            <div className="bg-[none] px-6  flex items-center justify-between  h-20 ">
              <div className="flex items-center space-x-2">
                <h1 className="textcolor text-2xl font-semibold">Good Morning,</h1>
                <div className="">
                <span className="textcolor text-2xl font-bold">John Doe</span>
              </div>

              </div>
              <div className="flex items-center justify-center">
                <Toolbox />
              </div>
            </div>



  
            {/* Page content*/}
            <div  className="flex-1 overflow-auto ml-4 mr-4">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
  
}
